# Generated by Django 3.2 on 2025-02-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='provedor',
            new_name='proveedor',
        ),
    ]
